version: "3.7"

services:
  store-management:
    depends_on:
      - mysql
    image: "${DOCKER_CREDS_USR}/sm:${BUILD_ID}"
    restart: on-failure
    ports:
      - 5552:5552
    environment:
      spring_profiles_active: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/store?createDatabaseIfNotExist=true


  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - sotre-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

volumes:
  sotre-mysql:
